//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    
    public enum AppointmentStatus : int
    {
        Scheduled = 1,
        Canceled = 2,
        Confirmed = 3,
        CheckedIn = 4,
        Ready = 5,
        InProgress = 6,
        Complete = 7,
        Hidden = 8
    }
}
