//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Address = new Address();
            this.Phone = new Phone();
            this.ZipCode = new ZipCode();
            this.Social = new Social();
            this.Address2 = new Address();
        }
    
        public int Id { get; set; }
        public int StateId { get; set; }
    
        public Address Address { get; set; }
        public Phone Phone { get; set; }
        public ZipCode ZipCode { get; set; }
        public Social Social { get; set; }
        public Address Address2 { get; set; }
    
        public virtual State State { get; set; }
    }
}
