//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCategory
    {
        public DocumentCategory()
        {
            this.Subcategories = new HashSet<DocumentSubcategory>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DocumentSubcategory> Subcategories { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
