//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVanity.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProcedure
    {
        public int Id { get; set; }
        public string PatientId { get; set; }
        public int ProcedureId { get; set; }
        public System.DateTime Date { get; set; }
        public ProcedureState State { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
